steps:
  # Terraform Init
  - name: hashicorp/terraform:1.7.5
    args:
      - init
      - '-input=false'

  # Terraform Plan
  - name: hashicorp/terraform:1.7.5
    args:
      - plan
      - '-input=false'
      - '-out=tfplan'
      - '-var-file=terraform.tfvars'

  # Terraform Apply (Automatic)
  - name: hashicorp/terraform:1.7.5
    args:
      - apply
      - '-input=false'
      - '-auto-approve'
      - 'tfplan'
